--- 
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_compact
output_dir: output

deploy:
  default:
    dst: "pla.to:/home/lordzork/vhosts/resume.pla.to"
    options: [ '-gpPrvz' ]			